import './globals.css'
import { Montserrat } from 'next/font/google'
import { Inter } from 'next/font/google'


const montserrat = Montserrat({
  weight: ['400','500','600','700','800'],
  subsets: ['latin'],
})
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Flowtify',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  )
}
